```yaml
services:
  - type: web
    name: flask-captcha
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: "<your_secret_key>"
      - key: RECAPTCHA_SITE_KEY
        value: "<your_site_key>"
      - key: RECAPTCHA_SECRET_KEY
        value: "<your_secret_key>"
    ports:
      - 5000
```