services:
  - type: web
    name: cybershieldlite
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: "<your_secret_key>"
      - key: RECAPTCHA_SITE_KEY
        value: "<your_site_key>"
      - key: RECAPTCHA_SECRET_KEY
        value: "<your_secret_key>"
      - key: SENTRY_DSN
        value: "<your_sentry_dsn>"    # optional
      - key: REDIS_URL
        fromDatabase:
          name: cybershield-redis
          property: url
    disks:
      - name: cybershield-data
        mountPath: /app

databases:
  - name: cybershield-redis
    engine: redis
    plan: free
