services:
  - type: web
    name: flask-captcha
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: "<your_secret_key>"
      - key: RECAPTCHA_SITE_KEY
        value: "<your_site_key>"
      - key: RECAPTCHA_SECRET_KEY
        value: "<your_secret_key>"
      - key: SENTRY_DSN
        value: "<your_sentry_dsn>"
      - key: REDIS_URL
        fromDatabase:
          name: flask-captcha-redis
          property: url
    disks:
      - name: captcha-data
        mountPath: /app

databases:
  - name: flask-captcha-redis
    engine: redis
    plan: free
